version: '3.8'
services:
  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt 
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt 
      - ./certbot/www:/var/www/certbot