version: '3.8'

services:
  pg:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - "./postgresql/data:/var/lib/postgresql/data"
      - "./init/:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
  node:
    depends_on:
      - pg
    build:
      dockerfile: Dockerfile
    image: server-node
    restart: unless-stopped
    ports:
      - "8000:8000"